# tempate number of shards
setup.template.settings:
  index.number_of_shards: 1

# Processing of the message
processors:
  - decode_json_fields:
      fields: ["message"]
      target: json
      process_array: false
      max_depth: 6
      overwrite_keys: true
      when:
        regexp:
          jsonmessage: '^\{'

# Filebeat input from beacon_events api call from spaceti
filebeat.inputs:
  ########################## adhochistory History Filebeats ###########################
  - type: httpjson
    url: http://localhost:3000/arbnco/adhochistory?pageSize=500&pageNumber=1&SITEID=${SITEID}
    http_method: GET
    interval: 60s
    timeout: 300s
    tags: ["beacon_events"]
    pagination:
      header:
        field_name: Link
        regex_pattern: '([^"]*)'

# output config to logstash at port 5024
# change the hosts array to the correct logstash server name
output.logstash:
   # The Logstash hosts
  hosts: ["localhost:5027"]
  timeout: 300s
  bulk_max_size: 204800


